version: '3'
services:
  todoDB:
    image: postgres:17.2
    container_name: todo-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=todo
